### PR TITLE
Change the upstream into the adobe one, deprecated our fork

### PR DESCRIPTION
**Pull request by dreampiggy**
See: https://github.com/SDWebImage/svg-native-viewer/pull/2

Found a new way (using Symbol Link) to solve this limit

### CODE REVIEW

**Comment by dreampiggy** [comment]
@tsapeta 

Please, upgrade to v0.1.0 to test if the SVG parsing works on your cases.

We dropped the old SDWebImage forked repo, use adobe usptream latest `main` instead.

**Comment by dreampiggy** [comment]
@tsapeta

Or, can you test the SVG rendering in https://github.com/SDWebImage/SDWebImageSVGNativeCoder Demo ?

You can added this sample into the Demo and check the result.

**Comment by tsapeta** [comment]
Thank you for handling this! Sure, I'll try to test this out over the weekend and then let you know 🙂

**Comment by dreampiggy** [comment]
Typo. 0.1.0

```
pod trunk info svgnative

svgnative
    - Versions:
      - 0.1.0 (2024-01-11 08:38:58 UTC)
      - 0.1.0-beta (2022-08-03 11:30:02 UTC)
    - Owners:
      - DreamPiggy <lizhuoli1126@126.com>
```

**Comment by dreampiggy** [comment]
Also, if you have macOS target which use `SDWebImageSVGNativeCoder`, you need to upgrade to the latest version as well.

**Pull request merged**
